

services:
  postgres:
    image: postgres:16-alpine
    container_name: vercel_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vercel_clone
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vercel_network

  redis:
    image: redis:latest
    container_name: vercel_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vercel_network

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: vercel_nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - vercel_network

  api:
    build:
      context: ./
      dockerfile: ./infra/docker/api.Dockerfile
    container_name: vercel_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vercel_network

 

  deployment:
    build:
      context: ./
      dockerfile: ./infra/docker/deployer.Dockerfile
    container_name: vercel_deployment
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vercel_network

volumes:
  postgres_data:

networks:
  vercel_network:
    driver: bridge